#############################################################################
# Makefile for building: Turbin
# Generated by qmake (2.01a) (Qt 4.8.7) on: Tue May 9 10:23:55 2017
# Project:  turbin.pro
# Template: subdirs
# Command: /usr/local/bin/qmake -o Makefile turbin.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = /usr/local/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub-external_library-easyloggingpp-easyloggingpp \
		sub-libglobal \
		sub-libdb \
		sub-libserver \
		sub-libgui \
		sub-turbin

external_library/easyloggingpp/easyloggingpp/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) external_library/easyloggingpp/easyloggingpp/ || $(MKDIR) external_library/easyloggingpp/easyloggingpp/ 
	cd external_library/easyloggingpp/easyloggingpp/ && $(QMAKE) /Users/apinprastya/Projects/qt/Turbin/external_library/easyloggingpp/easyloggingpp/easyloggingpp.pro -o $(MAKEFILE)
sub-external_library-easyloggingpp-easyloggingpp-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) external_library/easyloggingpp/easyloggingpp/ || $(MKDIR) external_library/easyloggingpp/easyloggingpp/ 
	cd external_library/easyloggingpp/easyloggingpp/ && $(QMAKE) /Users/apinprastya/Projects/qt/Turbin/external_library/easyloggingpp/easyloggingpp/easyloggingpp.pro -o $(MAKEFILE)
sub-external_library-easyloggingpp-easyloggingpp: external_library/easyloggingpp/easyloggingpp/$(MAKEFILE) FORCE
	cd external_library/easyloggingpp/easyloggingpp/ && $(MAKE) -f $(MAKEFILE)
sub-external_library-easyloggingpp-easyloggingpp-make_default-ordered: external_library/easyloggingpp/easyloggingpp/$(MAKEFILE) FORCE
	cd external_library/easyloggingpp/easyloggingpp/ && $(MAKE) -f $(MAKEFILE) 
sub-external_library-easyloggingpp-easyloggingpp-make_default: external_library/easyloggingpp/easyloggingpp/$(MAKEFILE) FORCE
	cd external_library/easyloggingpp/easyloggingpp/ && $(MAKE) -f $(MAKEFILE) 
sub-external_library-easyloggingpp-easyloggingpp-make_first-ordered: external_library/easyloggingpp/easyloggingpp/$(MAKEFILE) FORCE
	cd external_library/easyloggingpp/easyloggingpp/ && $(MAKE) -f $(MAKEFILE) first
sub-external_library-easyloggingpp-easyloggingpp-make_first: external_library/easyloggingpp/easyloggingpp/$(MAKEFILE) FORCE
	cd external_library/easyloggingpp/easyloggingpp/ && $(MAKE) -f $(MAKEFILE) first
sub-external_library-easyloggingpp-easyloggingpp-all-ordered: external_library/easyloggingpp/easyloggingpp/$(MAKEFILE) FORCE
	cd external_library/easyloggingpp/easyloggingpp/ && $(MAKE) -f $(MAKEFILE) all
sub-external_library-easyloggingpp-easyloggingpp-all: external_library/easyloggingpp/easyloggingpp/$(MAKEFILE) FORCE
	cd external_library/easyloggingpp/easyloggingpp/ && $(MAKE) -f $(MAKEFILE) all
sub-external_library-easyloggingpp-easyloggingpp-clean-ordered: external_library/easyloggingpp/easyloggingpp/$(MAKEFILE) FORCE
	cd external_library/easyloggingpp/easyloggingpp/ && $(MAKE) -f $(MAKEFILE) clean
sub-external_library-easyloggingpp-easyloggingpp-clean: external_library/easyloggingpp/easyloggingpp/$(MAKEFILE) FORCE
	cd external_library/easyloggingpp/easyloggingpp/ && $(MAKE) -f $(MAKEFILE) clean
sub-external_library-easyloggingpp-easyloggingpp-distclean-ordered: external_library/easyloggingpp/easyloggingpp/$(MAKEFILE) FORCE
	cd external_library/easyloggingpp/easyloggingpp/ && $(MAKE) -f $(MAKEFILE) distclean
sub-external_library-easyloggingpp-easyloggingpp-distclean: external_library/easyloggingpp/easyloggingpp/$(MAKEFILE) FORCE
	cd external_library/easyloggingpp/easyloggingpp/ && $(MAKE) -f $(MAKEFILE) distclean
sub-external_library-easyloggingpp-easyloggingpp-install_subtargets-ordered: external_library/easyloggingpp/easyloggingpp/$(MAKEFILE) FORCE
	cd external_library/easyloggingpp/easyloggingpp/ && $(MAKE) -f $(MAKEFILE) install
sub-external_library-easyloggingpp-easyloggingpp-install_subtargets: external_library/easyloggingpp/easyloggingpp/$(MAKEFILE) FORCE
	cd external_library/easyloggingpp/easyloggingpp/ && $(MAKE) -f $(MAKEFILE) install
sub-external_library-easyloggingpp-easyloggingpp-uninstall_subtargets-ordered: external_library/easyloggingpp/easyloggingpp/$(MAKEFILE) FORCE
	cd external_library/easyloggingpp/easyloggingpp/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-external_library-easyloggingpp-easyloggingpp-uninstall_subtargets: external_library/easyloggingpp/easyloggingpp/$(MAKEFILE) FORCE
	cd external_library/easyloggingpp/easyloggingpp/ && $(MAKE) -f $(MAKEFILE) uninstall
libglobal/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) libglobal/ || $(MKDIR) libglobal/ 
	cd libglobal/ && $(QMAKE) /Users/apinprastya/Projects/qt/Turbin/libglobal/libglobal.pro -o $(MAKEFILE)
sub-libglobal-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) libglobal/ || $(MKDIR) libglobal/ 
	cd libglobal/ && $(QMAKE) /Users/apinprastya/Projects/qt/Turbin/libglobal/libglobal.pro -o $(MAKEFILE)
sub-libglobal: libglobal/$(MAKEFILE) FORCE
	cd libglobal/ && $(MAKE) -f $(MAKEFILE)
sub-libglobal-make_default-ordered: libglobal/$(MAKEFILE) sub-external_library-easyloggingpp-easyloggingpp-make_default-ordered  FORCE
	cd libglobal/ && $(MAKE) -f $(MAKEFILE) 
sub-libglobal-make_default: libglobal/$(MAKEFILE) FORCE
	cd libglobal/ && $(MAKE) -f $(MAKEFILE) 
sub-libglobal-make_first-ordered: libglobal/$(MAKEFILE) sub-external_library-easyloggingpp-easyloggingpp-make_first-ordered  FORCE
	cd libglobal/ && $(MAKE) -f $(MAKEFILE) first
sub-libglobal-make_first: libglobal/$(MAKEFILE) FORCE
	cd libglobal/ && $(MAKE) -f $(MAKEFILE) first
sub-libglobal-all-ordered: libglobal/$(MAKEFILE) sub-external_library-easyloggingpp-easyloggingpp-all-ordered  FORCE
	cd libglobal/ && $(MAKE) -f $(MAKEFILE) all
sub-libglobal-all: libglobal/$(MAKEFILE) FORCE
	cd libglobal/ && $(MAKE) -f $(MAKEFILE) all
sub-libglobal-clean-ordered: libglobal/$(MAKEFILE) sub-external_library-easyloggingpp-easyloggingpp-clean-ordered  FORCE
	cd libglobal/ && $(MAKE) -f $(MAKEFILE) clean
sub-libglobal-clean: libglobal/$(MAKEFILE) FORCE
	cd libglobal/ && $(MAKE) -f $(MAKEFILE) clean
sub-libglobal-distclean-ordered: libglobal/$(MAKEFILE) sub-external_library-easyloggingpp-easyloggingpp-distclean-ordered  FORCE
	cd libglobal/ && $(MAKE) -f $(MAKEFILE) distclean
sub-libglobal-distclean: libglobal/$(MAKEFILE) FORCE
	cd libglobal/ && $(MAKE) -f $(MAKEFILE) distclean
sub-libglobal-install_subtargets-ordered: libglobal/$(MAKEFILE) sub-external_library-easyloggingpp-easyloggingpp-install_subtargets-ordered  FORCE
	cd libglobal/ && $(MAKE) -f $(MAKEFILE) install
sub-libglobal-install_subtargets: libglobal/$(MAKEFILE) FORCE
	cd libglobal/ && $(MAKE) -f $(MAKEFILE) install
sub-libglobal-uninstall_subtargets-ordered: libglobal/$(MAKEFILE) sub-external_library-easyloggingpp-easyloggingpp-uninstall_subtargets-ordered  FORCE
	cd libglobal/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-libglobal-uninstall_subtargets: libglobal/$(MAKEFILE) FORCE
	cd libglobal/ && $(MAKE) -f $(MAKEFILE) uninstall
libdb/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) libdb/ || $(MKDIR) libdb/ 
	cd libdb/ && $(QMAKE) /Users/apinprastya/Projects/qt/Turbin/libdb/libdb.pro -o $(MAKEFILE)
sub-libdb-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) libdb/ || $(MKDIR) libdb/ 
	cd libdb/ && $(QMAKE) /Users/apinprastya/Projects/qt/Turbin/libdb/libdb.pro -o $(MAKEFILE)
sub-libdb: libdb/$(MAKEFILE) FORCE
	cd libdb/ && $(MAKE) -f $(MAKEFILE)
sub-libdb-make_default-ordered: libdb/$(MAKEFILE) sub-libglobal-make_default-ordered  FORCE
	cd libdb/ && $(MAKE) -f $(MAKEFILE) 
sub-libdb-make_default: libdb/$(MAKEFILE) FORCE
	cd libdb/ && $(MAKE) -f $(MAKEFILE) 
sub-libdb-make_first-ordered: libdb/$(MAKEFILE) sub-libglobal-make_first-ordered  FORCE
	cd libdb/ && $(MAKE) -f $(MAKEFILE) first
sub-libdb-make_first: libdb/$(MAKEFILE) FORCE
	cd libdb/ && $(MAKE) -f $(MAKEFILE) first
sub-libdb-all-ordered: libdb/$(MAKEFILE) sub-libglobal-all-ordered  FORCE
	cd libdb/ && $(MAKE) -f $(MAKEFILE) all
sub-libdb-all: libdb/$(MAKEFILE) FORCE
	cd libdb/ && $(MAKE) -f $(MAKEFILE) all
sub-libdb-clean-ordered: libdb/$(MAKEFILE) sub-libglobal-clean-ordered  FORCE
	cd libdb/ && $(MAKE) -f $(MAKEFILE) clean
sub-libdb-clean: libdb/$(MAKEFILE) FORCE
	cd libdb/ && $(MAKE) -f $(MAKEFILE) clean
sub-libdb-distclean-ordered: libdb/$(MAKEFILE) sub-libglobal-distclean-ordered  FORCE
	cd libdb/ && $(MAKE) -f $(MAKEFILE) distclean
sub-libdb-distclean: libdb/$(MAKEFILE) FORCE
	cd libdb/ && $(MAKE) -f $(MAKEFILE) distclean
sub-libdb-install_subtargets-ordered: libdb/$(MAKEFILE) sub-libglobal-install_subtargets-ordered  FORCE
	cd libdb/ && $(MAKE) -f $(MAKEFILE) install
sub-libdb-install_subtargets: libdb/$(MAKEFILE) FORCE
	cd libdb/ && $(MAKE) -f $(MAKEFILE) install
sub-libdb-uninstall_subtargets-ordered: libdb/$(MAKEFILE) sub-libglobal-uninstall_subtargets-ordered  FORCE
	cd libdb/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-libdb-uninstall_subtargets: libdb/$(MAKEFILE) FORCE
	cd libdb/ && $(MAKE) -f $(MAKEFILE) uninstall
libserver/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) libserver/ || $(MKDIR) libserver/ 
	cd libserver/ && $(QMAKE) /Users/apinprastya/Projects/qt/Turbin/libserver/libserver.pro -o $(MAKEFILE)
sub-libserver-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) libserver/ || $(MKDIR) libserver/ 
	cd libserver/ && $(QMAKE) /Users/apinprastya/Projects/qt/Turbin/libserver/libserver.pro -o $(MAKEFILE)
sub-libserver: libserver/$(MAKEFILE) FORCE
	cd libserver/ && $(MAKE) -f $(MAKEFILE)
sub-libserver-make_default-ordered: libserver/$(MAKEFILE) sub-libdb-make_default-ordered  FORCE
	cd libserver/ && $(MAKE) -f $(MAKEFILE) 
sub-libserver-make_default: libserver/$(MAKEFILE) FORCE
	cd libserver/ && $(MAKE) -f $(MAKEFILE) 
sub-libserver-make_first-ordered: libserver/$(MAKEFILE) sub-libdb-make_first-ordered  FORCE
	cd libserver/ && $(MAKE) -f $(MAKEFILE) first
sub-libserver-make_first: libserver/$(MAKEFILE) FORCE
	cd libserver/ && $(MAKE) -f $(MAKEFILE) first
sub-libserver-all-ordered: libserver/$(MAKEFILE) sub-libdb-all-ordered  FORCE
	cd libserver/ && $(MAKE) -f $(MAKEFILE) all
sub-libserver-all: libserver/$(MAKEFILE) FORCE
	cd libserver/ && $(MAKE) -f $(MAKEFILE) all
sub-libserver-clean-ordered: libserver/$(MAKEFILE) sub-libdb-clean-ordered  FORCE
	cd libserver/ && $(MAKE) -f $(MAKEFILE) clean
sub-libserver-clean: libserver/$(MAKEFILE) FORCE
	cd libserver/ && $(MAKE) -f $(MAKEFILE) clean
sub-libserver-distclean-ordered: libserver/$(MAKEFILE) sub-libdb-distclean-ordered  FORCE
	cd libserver/ && $(MAKE) -f $(MAKEFILE) distclean
sub-libserver-distclean: libserver/$(MAKEFILE) FORCE
	cd libserver/ && $(MAKE) -f $(MAKEFILE) distclean
sub-libserver-install_subtargets-ordered: libserver/$(MAKEFILE) sub-libdb-install_subtargets-ordered  FORCE
	cd libserver/ && $(MAKE) -f $(MAKEFILE) install
sub-libserver-install_subtargets: libserver/$(MAKEFILE) FORCE
	cd libserver/ && $(MAKE) -f $(MAKEFILE) install
sub-libserver-uninstall_subtargets-ordered: libserver/$(MAKEFILE) sub-libdb-uninstall_subtargets-ordered  FORCE
	cd libserver/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-libserver-uninstall_subtargets: libserver/$(MAKEFILE) FORCE
	cd libserver/ && $(MAKE) -f $(MAKEFILE) uninstall
libgui/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) libgui/ || $(MKDIR) libgui/ 
	cd libgui/ && $(QMAKE) /Users/apinprastya/Projects/qt/Turbin/libgui/libgui.pro -o $(MAKEFILE)
sub-libgui-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) libgui/ || $(MKDIR) libgui/ 
	cd libgui/ && $(QMAKE) /Users/apinprastya/Projects/qt/Turbin/libgui/libgui.pro -o $(MAKEFILE)
sub-libgui: libgui/$(MAKEFILE) FORCE
	cd libgui/ && $(MAKE) -f $(MAKEFILE)
sub-libgui-make_default-ordered: libgui/$(MAKEFILE) sub-libserver-make_default-ordered  FORCE
	cd libgui/ && $(MAKE) -f $(MAKEFILE) 
sub-libgui-make_default: libgui/$(MAKEFILE) FORCE
	cd libgui/ && $(MAKE) -f $(MAKEFILE) 
sub-libgui-make_first-ordered: libgui/$(MAKEFILE) sub-libserver-make_first-ordered  FORCE
	cd libgui/ && $(MAKE) -f $(MAKEFILE) first
sub-libgui-make_first: libgui/$(MAKEFILE) FORCE
	cd libgui/ && $(MAKE) -f $(MAKEFILE) first
sub-libgui-all-ordered: libgui/$(MAKEFILE) sub-libserver-all-ordered  FORCE
	cd libgui/ && $(MAKE) -f $(MAKEFILE) all
sub-libgui-all: libgui/$(MAKEFILE) FORCE
	cd libgui/ && $(MAKE) -f $(MAKEFILE) all
sub-libgui-clean-ordered: libgui/$(MAKEFILE) sub-libserver-clean-ordered  FORCE
	cd libgui/ && $(MAKE) -f $(MAKEFILE) clean
sub-libgui-clean: libgui/$(MAKEFILE) FORCE
	cd libgui/ && $(MAKE) -f $(MAKEFILE) clean
sub-libgui-distclean-ordered: libgui/$(MAKEFILE) sub-libserver-distclean-ordered  FORCE
	cd libgui/ && $(MAKE) -f $(MAKEFILE) distclean
sub-libgui-distclean: libgui/$(MAKEFILE) FORCE
	cd libgui/ && $(MAKE) -f $(MAKEFILE) distclean
sub-libgui-install_subtargets-ordered: libgui/$(MAKEFILE) sub-libserver-install_subtargets-ordered  FORCE
	cd libgui/ && $(MAKE) -f $(MAKEFILE) install
sub-libgui-install_subtargets: libgui/$(MAKEFILE) FORCE
	cd libgui/ && $(MAKE) -f $(MAKEFILE) install
sub-libgui-uninstall_subtargets-ordered: libgui/$(MAKEFILE) sub-libserver-uninstall_subtargets-ordered  FORCE
	cd libgui/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-libgui-uninstall_subtargets: libgui/$(MAKEFILE) FORCE
	cd libgui/ && $(MAKE) -f $(MAKEFILE) uninstall
turbin/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) turbin/ || $(MKDIR) turbin/ 
	cd turbin/ && $(QMAKE) /Users/apinprastya/Projects/qt/Turbin/turbin/turbin.pro -o $(MAKEFILE)
sub-turbin-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) turbin/ || $(MKDIR) turbin/ 
	cd turbin/ && $(QMAKE) /Users/apinprastya/Projects/qt/Turbin/turbin/turbin.pro -o $(MAKEFILE)
sub-turbin: turbin/$(MAKEFILE) FORCE
	cd turbin/ && $(MAKE) -f $(MAKEFILE)
sub-turbin-make_default-ordered: turbin/$(MAKEFILE) sub-libgui-make_default-ordered  FORCE
	cd turbin/ && $(MAKE) -f $(MAKEFILE) 
sub-turbin-make_default: turbin/$(MAKEFILE) FORCE
	cd turbin/ && $(MAKE) -f $(MAKEFILE) 
sub-turbin-make_first-ordered: turbin/$(MAKEFILE) sub-libgui-make_first-ordered  FORCE
	cd turbin/ && $(MAKE) -f $(MAKEFILE) first
sub-turbin-make_first: turbin/$(MAKEFILE) FORCE
	cd turbin/ && $(MAKE) -f $(MAKEFILE) first
sub-turbin-all-ordered: turbin/$(MAKEFILE) sub-libgui-all-ordered  FORCE
	cd turbin/ && $(MAKE) -f $(MAKEFILE) all
sub-turbin-all: turbin/$(MAKEFILE) FORCE
	cd turbin/ && $(MAKE) -f $(MAKEFILE) all
sub-turbin-clean-ordered: turbin/$(MAKEFILE) sub-libgui-clean-ordered  FORCE
	cd turbin/ && $(MAKE) -f $(MAKEFILE) clean
sub-turbin-clean: turbin/$(MAKEFILE) FORCE
	cd turbin/ && $(MAKE) -f $(MAKEFILE) clean
sub-turbin-distclean-ordered: turbin/$(MAKEFILE) sub-libgui-distclean-ordered  FORCE
	cd turbin/ && $(MAKE) -f $(MAKEFILE) distclean
sub-turbin-distclean: turbin/$(MAKEFILE) FORCE
	cd turbin/ && $(MAKE) -f $(MAKEFILE) distclean
sub-turbin-install_subtargets-ordered: turbin/$(MAKEFILE) sub-libgui-install_subtargets-ordered  FORCE
	cd turbin/ && $(MAKE) -f $(MAKEFILE) install
sub-turbin-install_subtargets: turbin/$(MAKEFILE) FORCE
	cd turbin/ && $(MAKE) -f $(MAKEFILE) install
sub-turbin-uninstall_subtargets-ordered: turbin/$(MAKEFILE) sub-libgui-uninstall_subtargets-ordered  FORCE
	cd turbin/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-turbin-uninstall_subtargets: turbin/$(MAKEFILE) FORCE
	cd turbin/ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: turbin.pro  /usr/local/Cellar/qt/4.8.7_2/mkspecs/unsupported/macx-clang-libc++/qmake.conf /usr/local/Cellar/qt/4.8.7_2/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/common/gcc-base-macx.conf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/common/clang.conf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/qt_functions.prf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/qt_config.prf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/exclusive_builds.prf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/default_pre.prf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/mac/default_pre.prf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/release.prf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/default_post.prf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/mac/default_post.prf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/mac/x86_64.prf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/mac/objective_c.prf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/shared.prf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/warn_on.prf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/qt.prf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/unix/thread.prf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/moc.prf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/mac/rez.prf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/mac/sdk.prf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/resources.prf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/uic.prf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/yacc.prf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/lex.prf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/include_source_dir.prf
	$(QMAKE) -o Makefile turbin.pro
/usr/local/Cellar/qt/4.8.7_2/mkspecs/common/unix.conf:
/usr/local/Cellar/qt/4.8.7_2/mkspecs/common/mac.conf:
/usr/local/Cellar/qt/4.8.7_2/mkspecs/common/gcc-base.conf:
/usr/local/Cellar/qt/4.8.7_2/mkspecs/common/gcc-base-macx.conf:
/usr/local/Cellar/qt/4.8.7_2/mkspecs/common/clang.conf:
/usr/local/Cellar/qt/4.8.7_2/mkspecs/qconfig.pri:
/usr/local/Cellar/qt/4.8.7_2/mkspecs/modules/qt_webkit_version.pri:
/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/qt_functions.prf:
/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/qt_config.prf:
/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/exclusive_builds.prf:
/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/default_pre.prf:
/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/mac/default_pre.prf:
/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/release.prf:
/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/default_post.prf:
/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/mac/default_post.prf:
/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/mac/x86_64.prf:
/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/mac/objective_c.prf:
/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/shared.prf:
/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/warn_on.prf:
/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/qt.prf:
/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/unix/thread.prf:
/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/moc.prf:
/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/mac/rez.prf:
/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/mac/sdk.prf:
/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/resources.prf:
/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/uic.prf:
/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/yacc.prf:
/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/lex.prf:
/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -o Makefile turbin.pro

qmake_all: sub-external_library-easyloggingpp-easyloggingpp-qmake_all sub-libglobal-qmake_all sub-libdb-qmake_all sub-libserver-qmake_all sub-libgui-qmake_all sub-turbin-qmake_all FORCE

make_default: sub-external_library-easyloggingpp-easyloggingpp-make_default-ordered sub-libglobal-make_default-ordered sub-libdb-make_default-ordered sub-libserver-make_default-ordered sub-libgui-make_default-ordered sub-turbin-make_default-ordered FORCE
make_first: sub-external_library-easyloggingpp-easyloggingpp-make_first-ordered sub-libglobal-make_first-ordered sub-libdb-make_first-ordered sub-libserver-make_first-ordered sub-libgui-make_first-ordered sub-turbin-make_first-ordered FORCE
all: sub-external_library-easyloggingpp-easyloggingpp-all-ordered sub-libglobal-all-ordered sub-libdb-all-ordered sub-libserver-all-ordered sub-libgui-all-ordered sub-turbin-all-ordered FORCE
clean: sub-external_library-easyloggingpp-easyloggingpp-clean-ordered sub-libglobal-clean-ordered sub-libdb-clean-ordered sub-libserver-clean-ordered sub-libgui-clean-ordered sub-turbin-clean-ordered FORCE
distclean: sub-external_library-easyloggingpp-easyloggingpp-distclean-ordered sub-libglobal-distclean-ordered sub-libdb-distclean-ordered sub-libserver-distclean-ordered sub-libgui-distclean-ordered sub-turbin-distclean-ordered FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-external_library-easyloggingpp-easyloggingpp-install_subtargets-ordered sub-libglobal-install_subtargets-ordered sub-libdb-install_subtargets-ordered sub-libserver-install_subtargets-ordered sub-libgui-install_subtargets-ordered sub-turbin-install_subtargets-ordered FORCE
uninstall_subtargets: sub-external_library-easyloggingpp-easyloggingpp-uninstall_subtargets-ordered sub-libglobal-uninstall_subtargets-ordered sub-libdb-uninstall_subtargets-ordered sub-libserver-uninstall_subtargets-ordered sub-libgui-uninstall_subtargets-ordered sub-turbin-uninstall_subtargets-ordered FORCE

sub-external_library-easyloggingpp-easyloggingpp-check_ordered: external_library/easyloggingpp/easyloggingpp/$(MAKEFILE)
	cd external_library/easyloggingpp/easyloggingpp/ && $(MAKE) -f $(MAKEFILE) check
sub-libglobal-check_ordered: libglobal/$(MAKEFILE) sub-external_library-easyloggingpp-easyloggingpp-check_ordered 
	cd libglobal/ && $(MAKE) -f $(MAKEFILE) check
sub-libdb-check_ordered: libdb/$(MAKEFILE) sub-libglobal-check_ordered 
	cd libdb/ && $(MAKE) -f $(MAKEFILE) check
sub-libserver-check_ordered: libserver/$(MAKEFILE) sub-libdb-check_ordered 
	cd libserver/ && $(MAKE) -f $(MAKEFILE) check
sub-libgui-check_ordered: libgui/$(MAKEFILE) sub-libserver-check_ordered 
	cd libgui/ && $(MAKE) -f $(MAKEFILE) check
sub-turbin-check_ordered: turbin/$(MAKEFILE) sub-libgui-check_ordered 
	cd turbin/ && $(MAKE) -f $(MAKEFILE) check
check: sub-external_library-easyloggingpp-easyloggingpp-check_ordered sub-libglobal-check_ordered sub-libdb-check_ordered sub-libserver-check_ordered sub-libgui-check_ordered sub-turbin-check_ordered

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

