ALTER TABLE `customercredits` ADD COLUMN `flag` INT NOT NULL DEFAULT 0;
ALTER TABLE `customerrewards` ADD COLUMN `flag` INT NOT NULL DEFAULT 0;
ALTER TABLE `customers` ADD COLUMN `flag` INT NOT NULL DEFAULT 0;